dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - pip install -r requirements-dev.txt
  - pip install -e ./

script:
  - pylint cons/ tests/
  - if [[ `command -v black` ]]; then
      black --check cons tests;
    fi
  - pytest -v tests/ --cov=cons/

after_success:
  - pip install coveralls
  - coveralls -v
